# AInstein AI Assistant - Docker Compose Configuration
version: '3.8'

services:
  ainstein-assistant:
    build: .
    ports:
      - "8000:8000"
    environment:
      - EA_LOG_LEVEL=INFO
      - LLM_PROVIDER=groq
    env_file:
      - .env
    volumes:
      - ./data:/app/data:ro  # Mount data as read-only
      - ./logs:/app/logs     # Mount logs for persistence
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for session storage
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Optional: PostgreSQL for persistent storage
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ainstein
      POSTGRES_USER: ainstein
      POSTGRES_PASSWORD: secure_password_here
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data: